
###Request Password Reset
POST http://localhost:3002/password/request-password-reset
Content-Type: application/json

{
    "email": "gamesmy177@gmail.com"
}

###RESET PASSWORD
POST  http://localhost:3002/password/reset-password
Content-Type: application/json

{   "email":"games",
    "resetCode": "843u8x",
    "newPassword": "@New1234"
}

