###GET ALL USERS
GET http://localhost:3002/user/all
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZmI3ZjU4Y2QtNGRiZC00MTRiLTgwOGUtNWY4NmY4YzFkYjkzIiwidXNlcm5hbWUiOiJkYW50ZSIsImVtYWlsIjoiZ2FtZXNteTE3N0BnbWFpbC5jb20iLCJwYXNzd29yZF9oYXNoIjoiJDJhJDA2JDhkZlp0aDRVaTVlYnpxdGNpVzVDUGUuYTd5bW5ObEowcEJNbFFYRkZscGF3QWR5RHVTNEV5Iiwicm9sZSI6ImF0dGVuZGVlIiwiZmlyc3RfbmFtZSI6IkRhbmllbCIsImxhc3RfbmFtZSI6IktpdGhla2EiLCJwaG9uZV9udW1iZXIiOiIwMTEzMjM0NjU2IiwicHJvZmlsZV9waWN0dXJlX3VybCI6bnVsbCwiaXNfZGVsZXRlZCI6ZmFsc2UsImNyZWF0ZWRfYXQiOiIyMDI0LTA3LTE5VDExOjA1OjAxLjg0M1oiLCJ1cGRhdGVkX2F0IjoiMjAyNC0wNy0xOVQxMTowNTowMS44NDNaIiwiaWF0IjoxNzIxNTExMzkyLCJleHAiOjE3MjE1MjIxOTJ9.lvySgtm8Ak23mfmHKem_PUG1lWKeSPL2WCpJwZ6t9fw

###GET PROFILE
GET http://localhost:3002/user/profile/
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZmI3ZjU4Y2QtNGRiZC00MTRiLTgwOGUtNWY4NmY4YzFkYjkzIiwidXNlcm5hbWUiOiJkYW50ZSIsImVtYWlsIjoiZ2FtZXNteTE3N0BnbWFpbC5jb20iLCJwYXNzd29yZF9oYXNoIjoiJDJhJDA2JDhkZlp0aDRVaTVlYnpxdGNpVzVDUGUuYTd5bW5ObEowcEJNbFFYRkZscGF3QWR5RHVTNEV5Iiwicm9sZSI6ImF0dGVuZGVlIiwiZmlyc3RfbmFtZSI6IkRhbmllbCIsImxhc3RfbmFtZSI6IktpdGhla2EiLCJwaG9uZV9udW1iZXIiOiIwMTEzMjM0NjU2IiwicHJvZmlsZV9waWN0dXJlX3VybCI6bnVsbCwiaXNfZGVsZXRlZCI6ZmFsc2UsImNyZWF0ZWRfYXQiOiIyMDI0LTA3LTE5VDExOjA1OjAxLjg0M1oiLCJ1cGRhdGVkX2F0IjoiMjAyNC0wNy0xOVQxMTowNTowMS44NDNaIiwiaWF0IjoxNzIxNTg3Mzk4LCJleHAiOjE3MjE1OTgxOTh9.CA4e_U9nwr0v91nB7fqY3uTallSmXGbu7UHxXeEV7pM

### UPDATE PROFILE
PUT http://localhost:3002/user/profile/
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZmI3ZjU4Y2QtNGRiZC00MTRiLTgwOGUtNWY4NmY4YzFkYjkzIiwidXNlcm5hbWUiOiJkYW50ZSIsImVtYWlsIjoiZ2FtZXNteTE3N0BnbWFpbC5jb20iLCJwYXNzd29yZF9oYXNoIjoiJDJhJDA2JDhkZlp0aDRVaTVlYnpxdGNpVzVDUGUuYTd5bW5ObEowcEJNbFFYRkZscGF3QWR5RHVTNEV5Iiwicm9sZSI6ImF0dGVuZGVlIiwiZmlyc3RfbmFtZSI6IkRhbmllbCIsImxhc3RfbmFtZSI6IktpdGhla2EiLCJwaG9uZV9udW1iZXIiOiIwMTEzMjM0NjU2IiwicHJvZmlsZV9waWN0dXJlX3VybCI6bnVsbCwiaXNfZGVsZXRlZCI6ZmFsc2UsImNyZWF0ZWRfYXQiOiIyMDI0LTA3LTE5VDExOjA1OjAxLjg0M1oiLCJ1cGRhdGVkX2F0IjoiMjAyNC0wNy0xOVQxMTowNTowMS44NDNaIiwiaWF0IjoxNzIxNTg3Mzk4LCJleHAiOjE3MjE1OTgxOTh9.CA4e_U9nwr0v91nB7fqY3uTallSmXGbu7UHxXeEV7pM

{ 
  "first_name": "Dan new",
  "last_name": "Kitheka",
  "email": "games@yopmail.com",
  "phone_number": "+254123566898",
  "profile_picture_url": "profile_picture_url"
 }

###SWITCH ROLE
POST http://localhost:3002/user/role
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZmI3ZjU4Y2QtNGRiZC00MTRiLTgwOGUtNWY4NmY4YzFkYjkzIiwidXNlcm5hbWUiOiJkYW50ZSIsImVtYWlsIjoiZ2FtZXNteTE3N0BnbWFpbC5jb20iLCJwYXNzd29yZF9oYXNoIjoiJDJhJDA2JDhkZlp0aDRVaTVlYnpxdGNpVzVDUGUuYTd5bW5ObEowcEJNbFFYRkZscGF3QWR5RHVTNEV5Iiwicm9sZSI6ImF0dGVuZGVlIiwiZmlyc3RfbmFtZSI6IkRhbmllbCIsImxhc3RfbmFtZSI6IktpdGhla2EiLCJwaG9uZV9udW1iZXIiOiIwMTEzMjM0NjU2IiwicHJvZmlsZV9waWN0dXJlX3VybCI6bnVsbCwiaXNfZGVsZXRlZCI6ZmFsc2UsImNyZWF0ZWRfYXQiOiIyMDI0LTA3LTE5VDExOjA1OjAxLjg0M1oiLCJ1cGRhdGVkX2F0IjoiMjAyNC0wNy0xOVQxMTowNTowMS44NDNaIiwiaWF0IjoxNzIxMzg3NDE0LCJleHAiOjE3MjEzOTgyMTR9.XlOETwmaME-u7X5nltsAncjEYhh4afAOqCRsDRtOJN8

{
  "user_id":"503fc952-f0f5-408f-b7a0-d83378a928a3",
  "role":"attendee"
}



###Request To be Manager
POST http://localhost:3002/user/request-manager
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZjlmMzlhMjktZjdhMC00OGM1LWIzODEtZmJiMTc3YzlmZDYyIiwidXNlcm5hbWUiOiJqb2hubmllIiwiZW1haWwiOiJqb2hubmRpY2h1MTA0QGdtYWlsLmNvbSIsInJvbGUiOiJhdHRlbmRlZSIsImlhdCI6MTcyMTg0NjQxMCwiZXhwIjoxNzIxODUwMDEwfQ.pfQoDNxZa3CayF7O7_uWvhgD6J6mSYjL2DzmsY83dSI

###ALL USER REQUESTS TO BE MANAGERS
GET http://localhost:3002/user/manager-requests
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMmUyMmU1ZWYtMjE2Zi00OWM3LWIwMTItMDY3NjcxZjQ1YWYyIiwidXNlcm5hbWUiOiJqb3NlQDEyIiwiZW1haWwiOiJqb3NlQGdtYWlsLmNvbSIsInJvbGUiOiJzdXBlcl9hZG1pbiIsImlhdCI6MTcyMTgzMDkwNSwiZXhwIjoxNzIxODM0NTA1fQ.5QvE1hwPaLMGCF5See-9yMGQHUA9iG_Zbh9xpvPAMms

###APPROVE USER TO BE MANAGER
PATCH http://localhost:3002/user/requests/29f956da-6abb-45df-8aa9-60e849c15992/approve
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZjlmMzlhMjktZjdhMC00OGM1LWIzODEtZmJiMTc3YzlmZDYyIiwidXNlcm5hbWUiOiJqb2hubmllIiwiZW1haWwiOiJqb2hubmRpY2h1MTA0QGdtYWlsLmNvbSIsInBhc3N3b3JkX2hhc2giOiIkMmEkMDYkT3F5RS4waGpvdy5jellTSDRhQ2lqT3Y0c05MLkcwRUk2OVNJZkxDSVJSRDVsbThpeWw4QksiLCJyb2xlIjoiYXR0ZW5kZWUiLCJmaXJzdF9uYW1lIjoiSm9obiIsImxhc3RfbmFtZSI6Ik5kaWNodSIsInBob25lX251bWJlciI6IjAxMTI3MzQ2NTYiLCJwcm9maWxlX3BpY3R1cmVfdXJsIjpudWxsLCJpc19kZWxldGVkIjpmYWxzZSwiY3JlYXRlZF9hdCI6IjIwMjQtMDctMThUMTY6MjA6MzQuMTQ1WiIsInVwZGF0ZWRfYXQiOiIyMDI0LTA3LTE4VDE2OjIwOjM0LjE0NVoiLCJpYXQiOjE3MjEzNzM5MjYsImV4cCI6MTcyMTM4NDcyNn0.oyC2tJJeg1YSnpIGutW8KeWtNiHdEwYR3frJpRMT2vY